const dayCards = document.querySelectorAll(".day-card");
const modal = document.getElementById("taskModal");
const closeModalButton = document.getElementById("closeModal");
const taskForm = document.getElementById("taskForm");

const selectedDayText = document.getElementById("selectedDay");
const subjectInput = document.getElementById("subject");
const lessonInput = document.getElementById("lesson");
const startTimeInput = document.getElementById("startTime");
const endTimeInput = document.getElementById("endTime");

let selectedDay = null;

const STORAGE_KEY = "studySchedule";

function openModal(dayCard) {
    selectedDay = dayCard;

        const dayName = dayCard.dataset.day;
            selectedDayText.textContent = `مهمة يوم ${dayName}`;

                modal.classList.add("show");
                    modal.setAttribute("aria-hidden", "false");

                        subjectInput.focus();
                        }

                        function closeModal() {
                            modal.classList.remove("show");
                                modal.setAttribute("aria-hidden", "true");

                                    taskForm.reset();
                                        selectedDay = null;
                                        }

                                        dayCards.forEach(card => {
                                            const addButton = card.querySelector(".add-task");

                                                addButton.addEventListener("click", () => {
                                                        openModal(card);
                                                            });
                                                            });

                                                            closeModalButton.addEventListener("click", closeModal);

                                                            modal.addEventListener("click", event => {
                                                                if (event.target === modal) {
                                                                        closeModal();
                                                                            }
                                                                            });

                                                                            taskForm.addEventListener("submit", event => {
                                                                                event.preventDefault();

                                                                                    if (!selectedDay) return;

                                                                                        const task = {
                                                                                                id: Date.now(),
                                                                                                        day: selectedDay.dataset.day,
                                                                                                                subject: subjectInput.value,
                                                                                                                        lesson: lessonInput.value.trim(),
                                                                                                                                start: startTimeInput.value,
                                                                                                                                        end: endTimeInput.value,
                                                                                                                                                completed: false
                                                                                                                                                    };

                                                                                                                                                        if (!task.lesson || !task.start || !task.end) {
                                                                                                                                                                return;
                                                                                                                                                                    }

                                                                                                                                                                        const tasks = getTasks();

                                                                                                                                                                            tasks.push(task);

                                                                                                                                                                                saveTasks(tasks);
                                                                                                                                                                                    renderTasks();

                                                                                                                                                                                        closeModal();
                                                                                                                                                                                        });

                                                                                                                                                                                        function getTasks() {
                                                                                                                                                                                            try {
                                                                                                                                                                                                    return JSON.parse(localStorage.getItem(STORAGE_KEY)) || [];
                                                                                                                                                                                                        } catch {
                                                                                                                                                                                                                return [];
                                                                                                                                                                                                                    }
                                                                                                                                                                                                                    }

                                                                                                                                                                                                                    function saveTasks(tasks) {
                                                                                                                                                                                                                        localStorage.setItem(STORAGE_KEY, JSON.stringify(tasks));
                                                                                                                                                                                                                        }

                                                                                                                                                                                                                        function renderTasks() {
                                                                                                                                                                                                                            const tasks = getTasks();

                                                                                                                                                                                                                                dayCards.forEach(card => {
                                                                                                                                                                                                                                        const tasksContainer = card.querySelector(".tasks");
                                                                                                                                                                                                                                                const dayName = card.dataset.day;

                                                                                                                                                                                                                                                        tasksContainer.innerHTML = "";

                                                                                                                                                                                                                                                                const dayTasks = tasks.filter(task => task.day === dayName);

                                                                                                                                                                                                                                                                        dayTasks.forEach(task => {
                                                                                                                                                                                                                                                                                    const taskElement = document.createElement("div");

                                                                                                                                                                                                                                                                                                taskElement.className = "task";

                                                                                                                                                                                                                                                                                                            if (task.completed) {
                                                                                                                                                                                                                                                                                                                            taskElement.classList.add("completed");
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                    taskElement.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                    <div class="task-info">
                                                                                                                                                                                                                                                                                                                                                                                        <span class="task-subject">${escapeHTML(task.subject)}</span>

                                                                                                                                                                                                                                                                                                                                                                                                            <strong>${escapeHTML(task.lesson)}</strong>

                                                                                                                                                                                                                                                                                                                                                                                                                                <small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        ⏰ ${escapeHTML(task.start)} - ${escapeHTML(task.end)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </small>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="task-buttons">

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class="complete-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="تم الإنجاز"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ✓
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    class="delete-btn"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            type="button"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    title="حذف"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                🗑️
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                `;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const completeButton =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            taskElement.querySelector(".complete-btn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const deleteButton =
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        taskElement.querySelector(".delete-btn");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    completeButton.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    toggleComplete(task.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            deleteButton.addEventListener("click", () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            deleteTask(task.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    tasksContainer.appendChild(taskElement);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                function toggleComplete(taskId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const tasks = getTasks();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const task = tasks.find(item => item.id === taskId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!task) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                task.completed = !task.completed;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saveTasks(tasks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderTasks();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function deleteTask(taskId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const tasks = getTasks();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const updatedTasks = tasks.filter(item => item.id !== taskId);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    saveTasks(updatedTasks);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        renderTasks();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function escapeHTML(text) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const div = document.createElement("div");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                div.textContent = text;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return div.innerHTML;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    renderTasks();